"""Added required tables

Revision ID: 170a15b62657
Revises: 
Create Date: 2021-11-10 13:54:26.857368

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '170a15b62657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('date_start', sa.Date(), nullable=True),
                    sa.Column('date_end', sa.Date(), nullable=True),
                    sa.Column('short_description', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('place', sa.String(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('event_categories')
    # ### end Alembic commands ###
